### ISSUE TITLE
下面这些加到哪里

### ISSUE THREAD

**Issue by 56025192** [kindboy/pocketReader#1]
文件说明
client: 小程序客户端相关代码 server: mock服务器相关逻辑及云函数

// 利用jsdists实现开发环境和发布环境不同的打包规则
// 以下只在开发环境中起效果
/* <remove trigger="prod"> */
import {
    test
} from '../../lib/api-mock';
/* </remove> */

// 以下只在prod环境中起效果
/* <jdists trigger="prod">
import { test } from '../../lib/api';
</jdists> */

**Comment by lfanglee** [comment]
这代码是用来区分开发环境和发布环境的，可以这么写：
![image](https://user-images.githubusercontent.com/9296187/50720616-4efbe200-10eb-11e9-88fa-0caf4f8b2566.png)

在开发环境下，生效的就是这一段
![image](https://user-images.githubusercontent.com/9296187/50720629-8ff3f680-10eb-11e9-8eb7-51c948d82616.png)

在生产环境下生效的就是这一段
![image](https://user-images.githubusercontent.com/9296187/50720633-b2860f80-10eb-11e9-9e83-8449c07bd212.png)

具体实现部分在gulpfile.js里面的这里
![image](https://user-images.githubusercontent.com/9296187/50720651-f37e2400-10eb-11e9-9505-7262598ffbf0.png)

**Comment by 56025192** [comment]
谢谢
